In [5]:
import pandas as pd

df = pd.read_csv('SMSSpamCollection', sep='\t', header=None, names=['label', 'message'])
df

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [6]:
# Transform label values to numbers
df['label'] = df.label.map({'ham': 0, 'spam': 1})
df

      label                                            message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567      1  This is the 2nd time we have tried 2 contact u...
5568      0               Will ü b going to esplanade fr home?
5569      0  Pity, * was in mood for that. So...any other s...
5570      0  The guy did some bitching but I acted like i'd...
5571      0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['message'], df['label'])

In [8]:
# Converting Text to numerical data - Bag of words concept
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer(stop_words='english')

In [18]:
# Train the train dataset
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)

In [19]:
# Transform the test dataset
X_test_dtm = vect.transform(X_test)

In [11]:
# View the feature names (vocabulary)
print("Vocabulary:", vect.get_feature_names_out())
print("Matrix Shape:", X_train_dtm.shape)
print("Matrix (dense format):", X_train_dtm.toarray())

Vocabulary: ['00' '000' '0121' ... 'èn' 'ú1' '〨ud']
Matrix Shape: (4179, 7177)
Matrix (dense format): [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]

In [12]:
import numpy as np
# Calculate sparsity of the matrix
print("Sparsity:", (1 - (np.count_nonzero(X_train_dtm.toarray()) / X_train_dtm.toarray().size)) * 100, "% of values are zero" )

Sparsity: 99.89110677427558 % of values are zero

In [13]:
from scipy.sparse import csr_matrix

print("Sparse matrix representation:")
print(csr_matrix(X_train_dtm))

Sparse matrix representation:
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 32660 stored elements and shape (4179, 7177)>
  Coords	Values
  (0, 3879)	1
  (0, 4196)	1
  (0, 5678)	1
  (0, 4865)	1
  (0, 3750)	1
  (0, 6482)	1
  (0, 3445)	1
  (1, 4865)	1
  (1, 6370)	1
  (1, 2593)	1
  (1, 1649)	1
  (1, 2978)	1
  (1, 4060)	1
  (1, 2273)	1
  (2, 3193)	1
  (2, 1131)	1
  (2, 3581)	1
  (2, 3363)	1
  (2, 3234)	1
  (2, 752)	1
  (2, 3908)	1
  (2, 6322)	2
  (2, 6850)	1
  (2, 1639)	1
  (2, 7102)	1
  :	:
  (4175, 4034)	1
  (4175, 1830)	1
  (4175, 4637)	1
  (4175, 6557)	1
  (4176, 2047)	1
  (4176, 6147)	1
  (4177, 5615)	1
  (4177, 3830)	1
  (4178, 3604)	1
  (4178, 6338)	1
  (4178, 2967)	1
  (4178, 7025)	1
  (4178, 1851)	1
  (4178, 5053)	1
  (4178, 1715)	1
  (4178, 2802)	1
  (4178, 2364)	1
  (4178, 1458)	1
  (4178, 1)	1
  (4178, 4199)	1
  (4178, 5195)	1
  (4178, 7097)	1
  (4178, 267)	1
  (4178, 4384)	1
  (4178, 140)	1

In [14]:
from sklearn.naive_bayes import MultinomialNB

# Train the model
nb = MultinomialNB()
nb.fit(X_train_dtm, y_train)

MultinomialNB()

In [20]:
predictions = nb.predict(X_test_dtm)
prediction_list = list(zip(X_test, predictions))
prediction_list

[('Life is more strict than teacher... Bcoz Teacher teaches lesson &amp; then conducts exam, But Life first conducts Exam &amp; then teaches Lessons. Happy morning. . .',
  np.int64(0)),
 ('As usual..iam fine, happy &amp; doing well..:)', np.int64(0)),
 ('Just wait till end of march when el nino gets himself. Oh.', np.int64(0)),
 ("alright. Thanks for the advice. Enjoy your night out. I'ma try to get some sleep...",
  np.int64(0)),
 ('Good afternoon sexy buns! How goes the job search ? I wake and you are my first thought as always, my love. I wish your fine and happy and know I adore you!',
  np.int64(0)),
 ('I cant pick the phone right now. Pls send a message', np.int64(0)),
 ('I reach home safe n sound liao...', np.int64(0)),
 ('Hey cutie. How goes it? Here in WALES its kinda ok. There is like hills and shit but i still avent killed myself. ',
  np.int64(0)),
 ('Hi mom we might be back later than  &lt;#&gt; ', np.int64(0)),
 ("She said,'' do u mind if I go into the bedroom for a minute ? '' ''OK'', I sed in a sexy mood. She came out 5 minuts latr wid a cake...n My Wife,",
  np.int64(0)),
 ('For the most sparkling shopping breaks from 45 per person; call 0121 2025050 or visit www.shortbreaks.org.uk',
  np.int64(1)),
 ('Hi ....My engagement has been fixd on  &lt;#&gt; th of next month. I know its really shocking bt....hmm njan vilikkam....t ws al of a sudn;-(.',
  np.int64(0)),
 ('Ur cash-balance is currently 500 pounds - to maximize ur cash-in now send GO to 86688 only 150p/msg. CC 08718720201 HG/Suite342/2Lands Row/W1J6HL',
  np.int64(1)),
 ('Ummma.will call after check in.our life will begin from qatar so pls pray very hard.',
  np.int64(0)),
 ("I'm in town now so i'll jus take mrt down later.", np.int64(0)),
 ('Now got tv 2 watch meh? U no work today?', np.int64(0)),
 ("Can't. I feel nauseous. I'm so pissed. I didn't eat any sweets all week cause today I was planning to pig out. I was dieting all week. And now I'm not hungry :/",
  np.int64(0)),
 ('I just saw ron burgundy captaining a party boat so yeah', np.int64(0)),
 ('I know she called me', np.int64(0)),
 ('FREE entry into our £250 weekly comp just send the word ENTER to 84128 NOW. 18 T&C www.textcomp.com cust care 08712405020.',
  np.int64(1)),
 ("Send me yetty's number pls.", np.int64(0)),
 ('Umma my life and vava umma love you lot dear', np.int64(0)),
 ('I gotta collect da car at 6 lei.', np.int64(0)),
 ('Your brother is a genius', np.int64(0)),
 ('God picked up a flower and dippeditinaDEW, lovingly touched itwhichturnedinto u, and the he gifted tomeandsaid,THIS FRIEND IS 4U',
  np.int64(0)),
 ("K I'll be there before 4.", np.int64(0)),
 ('Eh sorry leh... I din c ur msg. Not sad already lar. Me watching tv now. U still in office?',
  np.int64(0)),
 ("Yes I posted a couple of pics on fb. There's still snow outside too. I'm just waking up :)",
  np.int64(0)),
 ("Ok that's great thanx a lot.", np.int64(0)),
 ('Say this slowly.? GOD,I LOVE YOU &amp; I NEED YOU,CLEAN MY HEART WITH YOUR BLOOD.Send this to Ten special people &amp; u c miracle tomorrow, do it,pls,pls do it...',
  np.int64(0)),
 ('Yo, call me when you get the chance, a friend of mine wanted me to ask you about a big order',
  np.int64(0)),
 ('Orh i tot u say she now still dun believe.', np.int64(0)),
 ('I am back. Bit long cos of accident on a30. Had to divert via wadebridge.I had a brilliant weekend thanks. Speak soon. Lots of love',
  np.int64(0)),
 ("Yeah I think my usual guy's still passed out from last night, if you get ahold of anybody let me know and I'll throw down",
  np.int64(0)),
 ('Valentines Day Special! Win over £1000 in our quiz and take your partner on the trip of a lifetime! Send GO to 83600 now. 150p/msg rcvd. CustCare:08718720201.',
  np.int64(1)),
 ("Thought praps you meant another one. Goodo! I'll look tomorrow ",
  np.int64(0)),
 ("I'm done. I'm sorry. I hope your next space gives you everything you want. Remember all the furniture is yours. If i'm not around when you move it, just lock all the locks and leave the key with jenne.",
  np.int64(0)),
 ("Neva mind it's ok..", np.int64(0)),
 ("By the way, 'rencontre' is to meet again. Mountains dont....", np.int64(0)),
 ("I only haf msn. It's yijue@hotmail.com", np.int64(0)),
 ('Good afternon, my love. How are today? I hope your good and maybe have some interviews. I wake and miss you babe. A passionate kiss from across the sea',
  np.int64(0)),
 ('K..k:)how much does it cost?', np.int64(0)),
 ('WINNER!! As a valued network customer you have been selected to receivea £900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.',
  np.int64(1)),
 ("Boo. How's things? I'm back at home and a little bored already :-(",
  np.int64(0)),
 ('Sorry about that this is my mates phone and i didnt write it love Kate',
  np.int64(0)),
 ('I think steyn surely get one wicket:)', np.int64(0)),
 ("Awesome, I'll see you in a bit", np.int64(0)),
 ('It shall be fine. I have avalarr now. Will hollalater', np.int64(0)),
 ('Love that holiday Monday feeling even if I have to go to the dentists in an hour',
  np.int64(0)),
 ('I‘ve got some salt, you can rub it in my open wounds if you like!',
  np.int64(0)),
 ('Then ur sis how?', np.int64(0)),
 ('Edison has rightly said, "A fool can ask more questions than a wise man can answer" Now you know why all of us are speechless during ViVa.. GM,GN,GE,GNT:-)',
  np.int64(0)),
 ('CALL 09090900040 & LISTEN TO EXTREME DIRTY LIVE CHAT GOING ON IN THE OFFICE RIGHT NOW TOTAL PRIVACY NO ONE KNOWS YOUR [sic] LISTENING 60P MIN 24/7MP 0870753331018+',
  np.int64(0)),
 ('So anyways, you can just go to your gym or whatever, my love *smiles* I hope your ok and having a good day babe ... I miss you so much already',
  np.int64(0)),
 ('If we win its really no 1 side for long time.', np.int64(0)),
 ("Id have to check but there's only like 1 bowls worth left", np.int64(0)),
 ('As a valued customer, I am pleased to advise you that following recent review of your Mob No. you are awarded with a £1500 Bonus Prize, call 09066364589',
  np.int64(1)),
 ('Dear relieved of westonzoyland, all going to plan this end too!',
  np.int64(0)),
 ("Yes. It's all innocent fun. O:-)", np.int64(0)),
 ("1 I don't have her number and 2 its gonna be a massive pain in the ass and i'd rather not get involved if that's possible",
  np.int64(0)),
 ('Ever thought about living a good life with a perfect partner? Just txt back NAME and AGE to join the mobile community. (100p/SMS)',
  np.int64(0)),
 ('Someone has contacted our dating service and entered your phone becausethey fancy you! To find out who it is call from a landline 09058098002. PoBox1, W14RG 150p',
  np.int64(1)),
 ('Dont forget you can place as many FREE Requests with 1stchoice.co.uk as you wish. For more Information call 08707808226.',
  np.int64(0)),
 ('Up to ü... Ü wan come then come lor... But i din c any stripes skirt...',
  np.int64(0)),
 ('England v Macedonia - dont miss the goals/team news. Txt ur national team to 87077 eg ENGLAND to 87077 Try:WALES, SCOTLAND 4txt/ú1.20 POBOXox36504W45WQ 16+',
  np.int64(1)),
 ('i am seeking a lady in the street and a freak in the sheets. Is that you?',
  np.int64(0)),
 ('Tell me pa. How is pain de.', np.int64(0)),
 ('Please CALL 08712402779 immediately as there is an urgent message waiting for you',
  np.int64(1)),
 ('Oh god..taken the teeth?is it paining', np.int64(0)),
 ('Dont hesitate. You know this is the second time she has had weakness like that. So keep i notebook of what she eat and did the day before or if anything changed the day before so that we can be sure its nothing',
  np.int64(0)),
 ('WHEN THE FIRST STRIKE IS A RED ONE. THE BIRD + ANTELOPE BEGIN TOPLAY IN THE FIELDOF SELFINDEPENDENCE BELIEVE THIS + THE FLOWER OF CONTENTION WILL GROW.RANDOM!',
  np.int64(0)),
 ("Wat's da model num of ur phone?", np.int64(0)),
 ("Quite ok but a bit ex... U better go eat smth now else i'll feel guilty...",
  np.int64(0)),
 ('How come guoyang go n tell her? Then u told her?', np.int64(0)),
 ('Pls speak with me. I wont ask anything other then you friendship.',
  np.int64(0)),
 ('I am hot n horny and willing I live local to you - text a reply to hear strt back from me 150p per msg Netcollex LtdHelpDesk: 02085076972 reply Stop to end',
  np.int64(1)),
 ('My sister in law, hope you are having a great month. Just saying hey. Abiola',
  np.int64(0)),
 ('Shall call now dear having food', np.int64(0)),
 ("Mah b, I'll pick it up tomorrow", np.int64(0)),
 ('What type of stuff do you sing?', np.int64(0)),
 ('Ü v ma fan...', np.int64(0)),
 ('Me n him so funny...', np.int64(0)),
 ('Dunno lei he neva say...', np.int64(0)),
 ('Yeah work is fine, started last week, all the same stuff as before, dull but easy and guys are fun!',
  np.int64(0)),
 ('Hmmm:)how many players selected?', np.int64(0)),
 ('4 tacos + 1 rajas burrito, right?', np.int64(0)),
 ('Nothing. Can...', np.int64(0)),
 ('44 7732584351, Do you want a New Nokia 3510i colour phone DeliveredTomorrow? With 300 free minutes to any mobile + 100 free texts + Free Camcorder reply or call 08000930705.',
  np.int64(1)),
 ('You still coming tonight?', np.int64(0)),
 ("So ü'll be submitting da project tmr rite?", np.int64(0)),
 ("My computer just fried the only essential part we don't keep spares of because my fucking idiot roommates looovvve leaving the thing running on full  &lt;#&gt; /7",
  np.int64(0)),
 ('Really dun bluff me leh... U sleep early too. Nite...', np.int64(0)),
 ('U still havent got urself a jacket ah?', np.int64(0)),
 ('Or remind me in a few hrs.', np.int64(0)),
 ('Call me da, i am waiting for your call.', np.int64(0)),
 ('PRIVATE! Your 2004 Account Statement for 07742676969 shows 786 unredeemed Bonus Points. To claim call 08719180248 Identifier Code: 45239 Expires',
  np.int64(1)),
 ('URGENT. Important information for 02 user. Today is your lucky day! 2 find out why , log onto http://www.urawinner.com there is a fantastic surprise awaiting you !',
  np.int64(1)),
 ('Wif my family booking tour package.', np.int64(0)),
 ('OH FUCK. JUSWOKE UP IN A BED ON A BOATIN THE DOCKS. SLEPT WID 25 YEAR OLD. SPINOUT! GIV U DA GOSSIP L8R. XXX',
  np.int64(0)),
 ('Will it help if we propose going back again tomorrow', np.int64(0)),
 ("As I entered my cabin my PA said, '' Happy B'day Boss !!''. I felt special. She askd me 4 lunch. After lunch she invited me to her apartment. We went there.",
  np.int64(0)),
 ('The evo. I just had to download flash. Jealous?', np.int64(0)),
 ('Miss call miss call khelate kintu opponenter miss call dhorte lage. Thats d rule. One with great phone receiving quality wins.',
  np.int64(0)),
 ('Shhhhh nobody is supposed to know!', np.int64(0)),
 ('Im good! I have been thinking about you...', np.int64(0)),
 ('Hey morning what you come to ask:-) pa...', np.int64(0)),
 ('Just chill for another 6hrs. If you could sleep the pain is not a surgical emergency so see how it unfolds. Okay',
  np.int64(0)),
 ('This pay is  &lt;DECIMAL&gt;  lakhs:)', np.int64(0)),
 ('i dnt wnt to tlk wid u', np.int64(0)),
 ('Nothing. I meant that once the money enters your account here, the bank will remove its flat rate. Someone transfered  &lt;#&gt;  to my account and  &lt;#&gt; dollars got removed. So the banks differ and charges also differ.be sure you trust the 9ja person you are sending account details to cos...',
  np.int64(0)),
 ('Ok i vl..do u know i got adsense approved..', np.int64(0)),
 ('Sorry! U can not unsubscribe yet. THE MOB offer package has a min term of 54 weeks> pls resubmit request after expiry. Reply THEMOB HELP 4 more info',
  np.int64(1)),
 ('Thats cool! I am a gentleman and will treat you with dignity and respect.',
  np.int64(0)),
 ("Oh for fuck's sake she's in like tallahassee", np.int64(0)),
 ('Sunshine Quiz! Win a super Sony DVD recorder if you canname the capital of Australia? Text MQUIZ to 82277. B',
  np.int64(1)),
 ('K da:)how many page you want?', np.int64(0)),
 ('Shopping? Eh ger i toking abt syd leh...Haha', np.int64(0)),
 ('Beautiful Truth against Gravity.. Read carefully: "Our heart feels light when someone is in it.. But it feels very heavy when someone leaves it.." GOODMORNING',
  np.int64(0)),
 ("That's fine, I'll bitch at you about it later then", np.int64(0)),
 ('Okie...', np.int64(0)),
 ('So the sun is anti sleep medicine.', np.int64(0)),
 ('whatever, im pretty pissed off.', np.int64(0)),
 ('Ok ill send you with in  &lt;DECIMAL&gt;  ok.', np.int64(0)),
 ("Party's at my place at usf, no charge (but if you can contribute in any way it is greatly appreciated) and yeah, we got room for one more",
  np.int64(0)),
 ("I think we're going to finn's now, come", np.int64(0)),
 ('Its ok my arm is feeling weak cuz i got a shot so we can go another time',
  np.int64(0)),
 ("What's up my own oga. Left my phone at home and just saw ur messages. Hope you are good. Have a great weekend.",
  np.int64(0)),
 ("Actually I decided I was too hungry so I haven't left yet :V", np.int64(0)),
 ('Customer place i will call you.', np.int64(0)),
 ('Some are lasting as much as 2 hours. You might get lucky.', np.int64(0)),
 ("I'm stuck in da middle of da row on da right hand side of da lt... ",
  np.int64(0)),
 ('Got meh... When?', np.int64(0)),
 ('Mom wants to know where you at', np.int64(0)),
 ('Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030',
  np.int64(1)),
 ('U WILL SWITCH YOUR FONE ON DAMMIT!!', np.int64(0)),
 ('Hey mate. Spoke to the mag people. We‘re on.  the is deliver by the end of the month. Deliver on the 24th sept. Talk later. ',
  np.int64(0)),
 ('Did you get any gift? This year i didnt get anything. So bad', np.int64(0)),
 ('Not yet chikku..k, then wat abt tht guy did he stopped irritating or msging to u..',
  np.int64(0)),
 ("How are you doing. How's the queen. Are you going for the royal wedding",
  np.int64(0)),
 ('Hi dis is yijue i would be happy to work wif ü all for gek1510...',
  np.int64(0)),
 ("Night sweet, sleep well! I've just been to see The Exorcism of Emily Rose and may never sleep again! Hugs and snogs! ",
  np.int64(0)),
 ('COME BACK TO TAMPA FFFFUUUUUUU', np.int64(0)),
 ("Joy's father is John. Then John is the ____ of Joy's father. If u ans ths you hav  &lt;#&gt;  IQ. Tis s IAS question try to answer.",
  np.int64(0)),
 ("jay says he'll put in  &lt;#&gt;", np.int64(0)),
 ("Watching tv lor... Y she so funny we bluff her 4 wat. Izzit because she thk it's impossible between us?",
  np.int64(0)),
 ('Message:some text missing* Sender:Name Missing* *Number Missing *Sent:Date missing *Missing U a lot thats y everything is missing sent via fullonsms.com',
  np.int64(0)),
 ("K..k..i'm also fine:)when will you complete the course?", np.int64(0)),
 ('Congrats! 1 year special cinema pass for 2 is yours. call 09061209465 now! C Suprman V, Matrix3, StarWars3, etc all 4 FREE! bx420-ip4-5we. 150pm. Dont miss out!',
  np.int64(1)),
 ('Mmm thats better now i got a roast down me! i\x92d b better if i had a few drinks down me 2! Good indian?',
  np.int64(0)),
 ('IM GONNAMISSU SO MUCH!!I WOULD SAY IL SEND U A POSTCARD BUTTHERES ABOUTAS MUCH CHANCE OF MEREMEMBERIN ASTHERE IS OFSI NOT BREAKIN HIS CONTRACT!! LUV Yaxx',
  np.int64(0)),
 ('tap & spile at seven. * Is that pub on gas st off broad st by canal. Ok?',
  np.int64(0)),
 ("No. Thank you. You've been wonderful", np.int64(0)),
 ("Aight that'll work, thanks", np.int64(0)),
 ('Ok lor ü reaching then message me.', np.int64(0)),
 ('Boy; I love u Grl: Hogolo Boy: gold chain kodstini Grl: Agalla Boy: necklace madstini Grl: agalla Boy: Hogli 1 mutai eerulli kodthini! Grl: I love U kano;-)',
  np.int64(0)),
 ('Okie.. Thanx..', np.int64(0)),
 ('Santa Calling! Would your little ones like a call from Santa Xmas eve? Call 09058094583 to book your time.',
  np.int64(0)),
 ("If you're not in my car in an hour and a half I'm going apeshit",
  np.int64(0)),
 ("Also hi wesley how've you been", np.int64(0)),
 ("Hello! How's you and how did saturday go? I was just texting to see if you'd decided to do anything tomo. Not that i'm trying to invite myself or anything!",
  np.int64(0)),
 ('XMAS iscoming & ur awarded either £500 CD gift vouchers & free entry 2 r £100 weekly draw txt MUSIC to 87066 TnC www.Ldew.com1win150ppmx3age16subscription ',
  np.int64(1)),
 ("its cool but tyler had to take off so we're gonna buy for him and drop it off at his place later tonight. Our total order is a quarter, you got enough?",
  np.int64(0)),
 ('Lol I would but despite these cramps I like being a girl.', np.int64(0)),
 ('Call Germany for only 1 pence per minute! Call from a fixed line via access number 0844 861 85 85. No prepayment. Direct access!',
  np.int64(1)),
 ('Imagine you finally get to sink into that bath after I have put you through your paces, maybe even having you eat me for a while before I left ... But also imagine the feel of that cage on your cock surrounded by the bath water, reminding you always who owns you ... Enjoy, my cuck',
  np.int64(0)),
 ("Lol no ouch but wish i'd stayed out a bit longer", np.int64(0)),
 ('Super da:)good replacement for murali', np.int64(0)),
 ('Do we have any spare power supplies', np.int64(0)),
 ('If you r @ home then come down within 5 min', np.int64(0)),
 ('Please attend the phone:)', np.int64(0)),
 ('Watch lor. I saw a few swatch one i thk quite ok. Ard 116 but i need 2nd opinion leh...',
  np.int64(0)),
 ('In which place do you want da.', np.int64(0)),
 ("You could have seen me..i did't recognise you Face.:)", np.int64(0)),
 ('I had askd u a question some hours before. Its answer', np.int64(0)),
 ("Yeah hopefully, if tyler can't do it I could maybe ask around a bit",
  np.int64(0)),
 ('Compliments to you. Was away from the system. How your side.', np.int64(0)),
 ('It‘s reassuring, in this crazy world.', np.int64(0)),
 ('I cant pick the phone right now. Pls send a message', np.int64(0)),
 ('Yo my trip got postponed, you still stocked up?', np.int64(0)),
 ('Argh my 3g is spotty, anyway the only thing I remember from the research we did was that province and sterling were the only problem-free places we looked at',
  np.int64(0)),
 ('(Bank of Granite issues Strong-Buy) EXPLOSIVE PICK FOR OUR MEMBERS *****UP OVER 300% *********** Nasdaq Symbol CDGT That is a $5.00 per..',
  np.int64(0)),
 ('Last Chance! Claim ur £150 worth of discount vouchers today! Text SHOP to 85023 now! SavaMob, offers mobile! T Cs SavaMob POBOX84, M263UZ. £3.00 Sub. 16',
  np.int64(1)),
 ('Sary just need Tim in the bollox &it hurt him a lot so he tol me!',
  np.int64(0)),
 ('Then ü come n pick me at 530 ar?', np.int64(0)),
 ('Hi, can i please get a  &lt;#&gt;  dollar loan from you. I.ll pay you back by mid february. Pls.',
  np.int64(0)),
 ("My sort code is  and acc no is . The bank is natwest. Can you reply to confirm i've sent this to the right person!",
  np.int64(0)),
 ('I was gonna ask you lol but i think its at 7', np.int64(0)),
 ('Think + da. You wil do.', np.int64(0)),
 ('hiya hows it going in sunny africa? hope u r avin a good time. give that big old silver back a big kiss from me.',
  np.int64(0)),
 ('Hi dear we saw dear. We both are happy. Where you my battery is low',
  np.int64(0)),
 ('A boy was late 2 home. His father: "POWER OF FRNDSHIP"', np.int64(0)),
 ('Guess what! Somebody you know secretly fancies you! Wanna find out who it is? Give us a call on 09065394973 from Landline DATEBox1282EssexCM61XN 150p/min 18',
  np.int64(1)),
 ('Haha... They cant what... At the most tmr forfeit... haha so how?',
  np.int64(0)),
 ('Yes we are chatting too.', np.int64(0)),
 ("Who's there say hi to our drugdealer", np.int64(0)),
 ('Just normal only here :)', np.int64(0)),
 ('No my blankets are sufficient, thx', np.int64(0)),
 ("Did either of you have any idea's? Do you know of anyplaces doing something?",
  np.int64(0)),
 ("I'm awake oh. What's up.", np.int64(0)),

In [21]:
# Evaluating the model
from sklearn import metrics

print("Accuracy:", metrics.accuracy_score(y_test, predictions))
print("Confusion matrix:\n", metrics.confusion_matrix(y_test, predictions))
print("Classification report:\n", metrics.classification_report(y_test, predictions))

Accuracy: 0.9856424982053122
Confusion matrix:
 [[1202    6]
 [  14  171]]
Classification report:
               precision    recall  f1-score   support

           0       0.99      1.00      0.99      1208
           1       0.97      0.92      0.94       185

    accuracy                           0.99      1393
   macro avg       0.98      0.96      0.97      1393
weighted avg       0.99      0.99      0.99      1393

In [22]:
# Make predictions on random messages
random_messages = ["You've Won!", "Hi, how are you?", "The IRS is Trying to Contact You",
                   "You Have a Refund Coming", "Verify Your Bank Account", "Love is in the air!",
                   "You Have a Package Delivery", "Boss Needs Help!", "A Family Member Needs Help",
                   "Are you up to go cinema?", "Let's go swimming"]
random_messages_dtm = vect.transform(random_messages)
predictions = nb.predict(random_messages_dtm)
prediction_list = list(zip(random_messages, predictions))
prediction_list

[("You've Won!", np.int64(0)),
 ('Hi, how are you?', np.int64(0)),
 ('The IRS is Trying to Contact You', np.int64(1)),
 ('You Have a Refund Coming', np.int64(0)),
 ('Verify Your Bank Account', np.int64(0)),
 ('Love is in the air!', np.int64(0)),
 ('You Have a Package Delivery', np.int64(1)),
 ('Boss Needs Help!', np.int64(0)),
 ('A Family Member Needs Help', np.int64(0)),
 ('Are you up to go cinema?', np.int64(0)),
 ("Let's go swimming", np.int64(0))]

In [23]:
right_answers = [1,0,1,1,1,0,1,1,1,0,0]
print("Accuracy:", metrics.accuracy_score(right_answers, predictions))
print("Confusion matrix:\n", metrics.confusion_matrix(right_answers, predictions))
print("Classification report:\n", metrics.classification_report(right_answers, predictions))

Accuracy: 0.5454545454545454
Confusion matrix:
 [[4 0]
 [5 2]]
Classification report:
               precision    recall  f1-score   support

           0       0.44      1.00      0.62         4
           1       1.00      0.29      0.44         7

    accuracy                           0.55        11
   macro avg       0.72      0.64      0.53        11
weighted avg       0.80      0.55      0.51        11

In [27]:
sms = input("Enter a message: ")
sms_dtm = vect.transform([sms])
prediction = nb.predict(sms_dtm)
if prediction[0] == 1:
    print("Spam")
else:
    print("Not spam")

Enter a message: fgsdufgeurfgukert
Not spam